import mongoose from "mongoose";

const transectionSchema = new mongoose.Schema(
  {
    fromAccount: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Account",
      required: [true, "Transection must be associated with a from account"],
      index: true,
    },
    toAccount: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Account",
      required: [true, "Transection must be associated with from account "],
      index: true,
    },
    status : {
      type: String,
      enum: {
        values: ["Pending", "Completed", "Faield", "Reversed"],
        message:
          "Status can be either Pending , Completed , Faield or Reversed",
      },
      default: "Pending",
    },
    amount: {
      type: Number,
      required: [true, "Amount is required for creating a transection"],
      min: [0, "Transection amount can not be negative"],
    },
    //this is only created one time for only one time transection and this is generated by the client side and use only one time and every time generate new id
    idempontencyKey: {
      type: String,
      required: [
        true,
        "Idempontency Key is required for creating a transection",
      ],
      index: true,
      unique: true,
    },
  },
  {
    timestamps: true,
  },
);

const transectionModel = mongoose.model("Transection", transectionSchema);

export default transectionModel;
